version: '3.8'
services:
  nginx:
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./
  server:
    build:  .
    container_name: "checklist-api-container"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3.8 main.py
